---
title: "Script_QC_MGF"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: html_document
---

```{r, echo=FALSE}
#REPLACE RELEASE 2 WITH THE PATH OF THE NEW RELEASE. 

release1_iden <- file.path(getwd(), "archive_all_2014-10/cache")
#release1_unid <- file.path(getwd(), "archive_all_2014-10/cache")

release2_iden <- file.path(getwd(), "archive_all_2016-10/archive_identified_2016-10/cache") 
release2_unid <- file.path(getwd(),"archive_all_2016-10/archive_unidentified_2016-10/cache")


```

```{r}
# PRIDE Cluster clusters all MS/MS spectra submitted to PRIDE Archive repository release: 2015-04
# http://www.ebi.ac.uk/pride/cluster/

# Description:The present script provides a reliable QC (Quality control) report about MGF files generated. 
# This script must be in the folder /nfs/nobackup/pride/cluster-prod/archive_spectra 

```

```{r, include=FALSE}
# Upload packages
packages <- c( "ggplot2", "scales", "knitr", "markdown", "tidyr", "rmarkdown","gridExtra", "stringr","data.table", "dplyr", "reshape")

if (length(setdiff(packages, rownames(installed.packages()))) > 0) {
    install.packages(setdiff(packages, rownames(installed.packages())))  }


library("ggplot2"); library("scales"); library("knitr"); library("markdown"); 
library("tidyr"); library("rmarkdown"); library("gridExtra"); library("stringr"); library("data.table"); library("dplyr"); library("reshape")
```


### **Number of peptides: **
#### **Release 1**

```{r, echo=FALSE}
#This part reads the files identify and unidentify ID and calculate how many peptides are in the last release
#and the current release
peptides_iden_release1 <- read.table(file.path(release1_iden, "ID_identify.txt"), quote="\"", comment.char="")
peptides_unid_release1 <- read.table(file.path(release1_iden, "ID_unidentify.txt"), quote="\"", comment.char="")


peptides_iden_release2 <- read.table(file.path(release2_iden, "ID_identify.txt"), quote="\"", comment.char="")
peptides_unid_release2 <- read.table(file.path(release2_unid, "ID_unidentify.txt"), quote="\"", comment.char="")


cat("The number of identified peptides in the release 1 is:", nrow(peptides_iden_release1))
cat("The number of unidentified peptides in the release 1 is:", nrow(peptides_unid_release1))

```

```{r, echo=FALSE, results='asis'}
#Print a frequency tables
table_release1 <- data.frame(Types = c("Identified", "Unidentified"), Peptides= c(nrow(peptides_iden_release1),nrow(peptides_unid_release1)) )

kable(table_release1, padding = 0)

```

#### **Release 2**


```{r, echo=FALSE}
cat("The number of identified peptides in the release 2 is:", nrow(peptides_iden_release2))
cat("The number of unidentified peptides in the release 2 is:", nrow(peptides_unid_release2))



```

```{r, echo=FALSE, results='asis'}
table_release2 <- data.frame(Types = c("Identified", "Unidentified"), Peptides= c(nrow(peptides_iden_release2),nrow(peptides_unid_release2)) )

kable(table_release2, padding = 0)




```

#### **Summary**

```{r, echo=FALSE, fig.width=10}

#Conditional
if (nrow(peptides_iden_release1)>nrow(peptides_iden_release2)) {
    cat("Number of identified peptides reduced:", nrow(peptides_iden_release1)-nrow(peptides_iden_release2),"\n")
} else if ((nrow(peptides_iden_release1)<nrow(peptides_iden_release2))) {
    cat("Number of identified Peptides increased:", nrow(peptides_iden_release2)-nrow(peptides_iden_release1),"\n")
} else
    cat("The number of identified peptides are equal \n")


if (nrow(peptides_unid_release1)>nrow(peptides_unid_release2)) {
    cat("Number of unidentified peptides reduced:", nrow(peptides_iden_release1)-nrow(peptides_iden_release2),"\n")
} else if ((nrow(peptides_unid_release1)<nrow(peptides_unid_release2))) {
    cat("Number of unidentified Peptides increased:", nrow(peptides_unid_release2)-nrow(peptides_unid_release1),"\n")
} else
    cat("The number of unidentified peptides are equal \n")


#Create a data.frame with the data. 
df_identified_peptides <- data.frame(Types = c("Release1\nIdentified", "Release2\nIdentified"), Peptides= c(nrow(peptides_iden_release1),nrow(peptides_iden_release2)) )

df_unidentified_peptides <- data.frame(Types = c("Release1\nUnidentified", "Release2\nUnidentified"), Peptides= c(nrow(peptides_unid_release1),nrow(peptides_unid_release2)))


#Bar plot
a <- ggplot(df_identified_peptides, aes(x = Types, y = Peptides, fill=Types)) + geom_bar(stat = "identity") + theme(axis.text.x=element_blank(),axis.ticks.x=element_blank()) + scale_y_continuous(expand = c(0, 1000)) 

b <- ggplot(df_unidentified_peptides, aes(x = Types, y = Peptides, fill=Types)) + geom_bar(stat = "identity") + theme(axis.text.x=element_blank(),axis.ticks.x=element_blank()) + scale_y_continuous(expand = c(0, 100)) 


grid.arrange(a, b, ncol=2)


```


### **Number of modifications: **
#### **Release 1**

```{r, echo=FALSE, message=FALSE, warning=FALSE}

#This part create a modificatons table with the number of medifications en each release and a comparative plot

modifications_release1 <- read.delim(file.path(release1_iden, "tables/modifications_table.txt"), header = FALSE)
modifications_release2 <- read.delim(file.path(release2_iden, "tables/modifications_table.txt"), header=FALSE)



colnames(modifications_release1) <- c("Modifications", "Frequency")
colnames(modifications_release2) <- c("Modifications", "Frequency")


modifications_release1_1 <- modifications_release1[order(modifications_release1$Modifications),] 
modifications_release2_2 <- modifications_release2[order(modifications_release2$Modifications),] 


modifications1 <- cbind(modifications_release1[1:(nrow(modifications_release1_1)/2),], modifications_release1[((nrow(modifications_release1_1)/2)+1):nrow(modifications_release1_1),]) 

modifications2 <- cbind(modifications_release2[1:(nrow(modifications_release2_2)/2),], modifications_release2[((nrow(modifications_release2)/2)+1):nrow(modifications_release2),]) 

cat("There are",nrow(modifications_release1), " different modifications")
cat("The number of modifications are:", sum(modifications_release1$Frequency))
kable(modifications1, row.names = FALSE, padding = 0)
```

#### **Release 2**

```{r, echo=FALSE}

cat("There are",nrow(modifications_release2), " different modifications")
cat("The number of modifications are:", sum(modifications_release2$Frequency))

kable(modifications2, row.names = FALSE, padding = 0)


```

#### **Summary**


```{r, echo=FALSE, message=FALSE, warning=FALSE}
#Conditional
if (nrow(modifications_release1)>nrow(modifications_release2)) {
    cat("Number of modifications reduced in the new release:", nrow(modifications_release1)-nrow(modifications_release2),"\n")
} else if ((nrow(modifications_release1)<nrow(modifications_release2))) {
    cat("Number of modifications increased in the new release:", nrow(modifications_release2)-nrow(modifications_release1),"\n")
} else
    cat("The number of identified peptides are equal \n")


#Create a df to make it easier
df <- modifications_release1
df2 <- modifications_release2

#First convert your peptide counts to numeric (they're a factor with numeric character labels, that's a bit messed up):

df$Frequency=as.numeric(as.character(df$Frequency))
df2$Frequency=as.numeric(as.character(df2$Frequency))


df_final<- df %>% 
    full_join(df2, by = "Modifications", suffix = c(".1", ".2")) %>%
    # Fix data to convert to character and numeric
    mutate_each(funs(as.numeric(as.character(.))), starts_with("pept")) %>%
    # See difference
    mutate(change = Frequency.2 - Frequency.1)

#How many new peptides are there  in the new release?. 
df_peptides <- df_final[is.na(df_final$Frequency.1),]
df_peptides2 <- data.frame(Modifications=df_peptides$Modifications, Frequency=df_peptides$Frequency.2)

df_peptides3 <- df_final[is.na(df_final$Frequency.2),]
df_peptides4 <- data.frame(Modifications=df_peptides3$Modifications, Frequency=df_peptides3$Frequency.2)

```

```{r, echo=FALSE, warning=FALSE}
#To know if the new release has obtained new peptides. 
if (nrow(df_final[is.na(df_final$Frequency.1),])!=0) {
    cat("The new release has obtained new peptides")
    kable(df_peptides2, padding = 0)
} else if (nrow(df_final[is.na(df_final$Frequency.2),])!=0) {
    cat("The new release has lost peptides\n")
    kable(df_peptides4, padding = 0)
} else
   cat("The new release has got the same peptides")



```


```{r, echo=FALSE}
#HISTOGRAM: 
#Para preparar el histograma tenemos que clasificar los tipos de modificaciones, POSICION-DATABA-ID. 
# Para ello cogemos los datos que no sean NULL y eliminamos los espacios en banco. 

histo1 = subset(df, Modifications != 'NULL')
histo1[histo1==""] <- NA
histo1 = subset(histo1, Modifications != 'NA')

histo1_2 = subset(df2, Modifications != 'NULL')
histo1_2[histo1_2==""] <- NA
histo1_2 = subset(histo1_2, Modifications != 'NA')

#Split dataset. 
histo2 <- data.frame(str_split_fixed(histo1$Modifications, ",", 20))
histo2_2 <- data.frame(str_split_fixed(histo1_2$Modifications, ",", 20))

#If you want to check how many columns are empty, you can use the code below: 
#columns_emply <- histo2[!sapply(histo2, function(x) all(x == ""))]
#columns_emply <- histo2_2[!sapply(histo2_2, function(x) all(x == ""))]

#Merge the columns in one. 
histo3 <- melt(setDT(histo2),                              # set df to a data.table
               measure.vars = list(c(1:20)),    # set column groupings
               value.name = 'V')[                      # set output name scheme
                   , -1, with = F]

histo3_2 <- melt(setDT(histo2_2),                              # set df to a data.table
                 measure.vars = list(c(1:20)),    # set column groupings
                 value.name = 'V')[                      # set output name scheme
                     , -1, with = F]

#Remove white rows.  
histo3[histo3==""] <- NA
histo3 = subset(histo3, V1 != " ")

histo3_2[histo3_2==""] <- NA
histo3_2 = subset(histo3_2, V1 != " ")

#Remove first part of the string [num]-
histo4 <- data.frame(modifications=gsub(" [A-Za-z] ", "", gsub("[0-9]*-", "", histo3$V1)))
histo4_2 <- data.frame(modifications.2=gsub(" [A-Za-z] ", "", gsub("[0-9]*-", "", histo3_2$V1)))

#Histograma: 
histo5 <- data.frame(table(histo4))
histo5_2 <- data.frame(table(histo4_2))

# ggplot(data=histo5, aes(x=histo4, y=Freq, fill=histo4)) +
#     geom_bar(stat="identity") + guides(fill=FALSE)+ 
#     theme(axis.text.x = element_text(angle = 90, hjust = 1))
# 
# ggplot(data=histo5_2, aes(x=histo4_2, y=Freq, fill=histo4_2)) +
#     geom_bar(stat="identity") + guides(fill=FALSE)+ 
#     theme(axis.text.x = element_text(angle = 90, hjust = 1))

```

```{r, echo=FALSE, fig.height=15, fig.width=25, message=FALSE, warning=FALSE}
#We're going to compare different releases in order to compare between them and create a stacker plot.

histo5 <- modifications_release1
histo5_2 <- modifications_release2

colnames(histo5) <- c("Modifications","Frequency")
colnames(histo5_2) <- c("Modifications","Frequency")

histo6<-merge(histo5,histo5_2, by = "Modifications",all = T)


histo7<- melt(histo6)
histo7$variable<-factor(histo7$variable,labels = c("Modifications1","Modifications2"))


ggplot(histo7, aes(x = Modifications, y = value, fill = variable)) + 
  geom_bar(stat = "identity",position = "dodge")+
    theme(axis.text.x = element_text(angle = 20, hjust = 0.5, vjust = -0.1)) + 
    guides(fill=FALSE)+
    labs("Barplot Release1 vs Release 2") + 
    xlab("Values")+
    ylab("Frequency")+
    theme(text = element_text(size=18), axis.text.x = element_text(angle = 90, hjust = 1, size = 15), 
          axis.text.y=element_text(size = 15))

```

### **Spectrum**

```{r, echo=FALSE, message=FALSE, warning=FALSE}
#Here is the same than before examples.

spectrum_iden_release1 <- read.delim(file.path(release1_iden, "tables/spectrum_ide_table.txt"), header = TRUE)
spectrum_unid_release1 <- read.delim(file.path(release1_iden, "tables/spectrum_unide_table.txt"), header=TRUE)

spectrum_iden_release2 <- read.delim(file.path(release2_iden, "tables/spectrum_ide_table.txt"), header = TRUE)
spectrum_unid_release2 <- read.delim(file.path(release2_unid, "tables/spectrum_unide_table.txt"), header=TRUE)

```

#### **Release 1 **
```{r, echo=FALSE, message=FALSE, warning=FALSE}
cat("The number of identified spectrum in the release 1 is:", spectrum_iden_release1$Spectrum.Number)
cat("The number of identified spectrum in the release2  is:", spectrum_iden_release2$Spectrum.Number)

```

#### **Release 2**
```{r, echo=FALSE, message=FALSE, warning=FALSE}
cat("The number of identified spectrum in the release 1 is:", spectrum_iden_release1$Spectrum.Number)
cat("The number of identified spectrum in the release2  is:", spectrum_iden_release2$Spectrum.Number)
```

#### **Summary**
```{r, echo=FALSE, message=FALSE, warning=FALSE}
#for identified
if (spectrum_iden_release1$Spectrum.Number>spectrum_iden_release2$Spectrum.Number) {
    cat("Number of identified spectrum reduced:", spectrum_iden_release1$Spectrum.Number-spectrum_iden_release2$Spectrum.Number,"\n")
} else if ((spectrum_iden_release1$Spectrum.Number<spectrum_iden_release2$Spectrum.Number)) {
    cat("Number of identified spectrum Peptides increased:", spectrum_iden_release2$Spectrum.Number-spectrum_iden_release1$Spectrum.Number,"\n")
} else
    cat("The number of identified spectrum is the same in both releases \n")


#For unidentified
if (spectrum_unid_release1$Spectrum.Number>spectrum_unid_release2$Spectrum.Number) {
    cat("Number of unidentified spectrum reduced:", spectrum_unid_release1$Spectrum.Number-spectrum_unid_release2$Spectrum.Number,"\n")
} else if ((spectrum_unid_release1$Spectrum.Number<spectrum_unid_release2$Spectrum.Number)) {
    cat("Number of unidentified spectrum Peptides increased:", spectrum_unid_release2$Spectrum.Number-spectrum_unid_release1$Spectrum.Number,"\n")
} else
    cat("The number of unidentified spectrum is the same in both releases \n")


```

### **Taxonomy** 
#### **Release 1**

```{r, echo=FALSE}

taxonomy_iden_release1 <- read.delim(file.path(release1_iden, "tables/taxonomy_ide_table.txt"), header = FALSE)
taxonomy_unid_release1 <- read.delim(file.path(release1_iden, "tables/taxonomy_unide_table.txt"), header=FALSE)

taxonomy_iden_release2 <- read.delim(file.path(release2_iden, "tables/taxonomy_ide_table.txt"), header = FALSE)
taxonomy_unid_release2 <- read.delim(file.path(release2_unid, "tables/taxonomy_unide_table.txt"), header=FALSE)

colnames(taxonomy_iden_release1) <- c("Taxonomy", "Frequency")
colnames(taxonomy_unid_release1) <- c("Taxonomy", "Frequency")
colnames(taxonomy_iden_release2) <- c("Taxonomy", "Frequency")
colnames(taxonomy_unid_release2) <- c("Taxonomy", "Frequency")


cat("Number of species in the release 1 is:", nrow(taxonomy_iden_release1))
cat("The total taxonomy for identified peptides in the release 1 is:", sum(taxonomy_iden_release1$Frequency))
cat("The total taxonomy for unidentified peptides in the release 1 is:", sum(taxonomy_unid_release1$Frequency))





```

#### **Release 2**

```{r, echo=FALSE}

cat("Number of species in the release 2 is:", nrow(taxonomy_iden_release2))
cat("The total taxonomy for identified peptides in the release 2 is:", sum(taxonomy_iden_release2$Frequency))
cat("The total taxonomy for unidentified peptides in the release 2 is:", sum(taxonomy_unid_release2$Frequency))





```

### **Summary**

```{r, echo=FALSE}

#Conditional
if (sum(taxonomy_iden_release1$Frequency)>sum(taxonomy_iden_release2$Frequency)) {
    cat("Identified peptides from Taxonomy reduced in the new release:", nrow(taxonomy_iden_release1$Frequency)-nrow(taxonomy_iden_release2$Frequency),"\n")
} else if ((sum(taxonomy_iden_release1$Frequency)<sum(taxonomy_iden_release2$Frequency))) {
    cat("Identified peptides from Taxonomy increased in the new release:", sum(taxonomy_iden_release2$Frequency)-sum(taxonomy_iden_release1$Frequency),"\n")
} else
    cat("Taxonomy peptides are equal in both releases \n")


#Conditional
if (sum(taxonomy_unid_release1$Frequency)>sum(taxonomy_unid_release2$Frequency)) {
    cat("Identified peptides from Taxonomy reduced in the new release:", nrow(taxonomy_unid_release1$Frequency)-nrow(taxonomy_unid_release2$Frequency),"\n")
} else if ((sum(taxonomy_unid_release1$Frequency)<sum(taxonomy_unid_release2$Frequency))) {
    cat("Identified peptides from Taxonomy increased in the new release:", sum(taxonomy_unid_release2$Frequency)-sum(taxonomy_unid_release1$Frequency),"\n")
} else
    cat("Taxonomy peptides are equal in both releases \n")
```

```{r, echo=FALSE}

taxonomy_iden_release1 <- read.delim(file.path(release1_iden, "tables/taxonomy_ide_table.txt"), header = FALSE)
taxonomy_unid_release1 <- read.delim(file.path(release1_iden, "tables/taxonomy_unide_table.txt"), header=FALSE)

taxonomy_iden_release2 <- read.delim(file.path(release2_iden, "tables/taxonomy_ide_table.txt"), header = FALSE)
taxonomy_unid_release2 <- read.delim(file.path(release2_unid, "tables/taxonomy_unide_table.txt"), header=FALSE)

colnames(taxonomy_iden_release1) <- c("Taxonomy", "Frequency")
colnames(taxonomy_unid_release1) <- c("Taxonomy", "Frequency")
colnames(taxonomy_iden_release2) <- c("Taxonomy", "Frequency")
colnames(taxonomy_unid_release2) <- c("Taxonomy", "Frequency")

taxonomy_iden_release1$Taxonomy <- as.factor(taxonomy_iden_release1$Taxonomy)
taxonomy_unid_release1$Taxonomy <- as.factor(taxonomy_unid_release1$Taxonomy)
taxonomy_iden_release2$Taxonomy <- as.factor(taxonomy_iden_release2$Taxonomy)
taxonomy_unid_release2$Taxonomy <- as.factor(taxonomy_unid_release2$Taxonomy)


#Create table
taxonomy_table_iden<-merge(taxonomy_iden_release1,taxonomy_iden_release2, by = "Taxonomy",all = T)
taxonomy_table_unid<-merge(taxonomy_unid_release1,taxonomy_unid_release2, by = "Taxonomy",all = T)

library(reshape2)
taxonomy_table_iden2<- melt(taxonomy_table_iden)
taxonomy_table_unid2<- melt(taxonomy_table_unid)


taxonomy_table_iden2$variable<-factor(taxonomy_table_iden2$variable,labels = c("Taxonomy1","Taxonomy2"))
taxonomy_table_unid2$variable<-factor(taxonomy_table_unid2$variable,labels = c("Taxonomy1","Taxonomy2"))



ggplot(taxonomy_table_iden2, aes(x = Taxonomy, y = value, fill = variable)) + 
  geom_bar(stat = "identity",position = "dodge")+
    theme(axis.text.x = element_text(angle = 20, hjust = 0.5, vjust = -0.1)) + 
    guides(fill=FALSE)+
    labs("Barplot Release1 vs Release 2") + 
    xlab("Values")+
    ggtitle("Identified Taxonomy")+
    ylab("Frequency")+
    theme(text = element_text(size=18), axis.text.x = element_text(angle = 90, hjust = 1, size = 15), 
          axis.text.y=element_text(size = 15))

ggplot(taxonomy_table_unid2, aes(x = Taxonomy, y = value, fill = variable)) + 
  geom_bar(stat = "identity",position = "dodge")+
    theme(axis.text.x = element_text(angle = 20, hjust = 0.5, vjust = -0.1)) + 
    guides(fill=FALSE)+
    labs("Barplot Release1 vs Release 2") + 
    ggtitle("Unidentified Taxonomy")+
    xlab("Values")+
    ylab("Frequency")+
    theme(text = element_text(size=18), axis.text.x = element_text(angle = 90, hjust = 1, size = 15), 
          axis.text.y=element_text(size = 15))


```

