---
title: "Script_QC_MGF"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: html_document
---

```{r}
# PRIDE Cluster clusters all MS/MS spectra submitted to PRIDE Archive repository release: 2015-04
# http://www.ebi.ac.uk/pride/cluster/

# Description:The present script provides a reliable QC (Quality control) report about MGF files generated. 
# This script must be in the folder /nfs/nobackup/pride/cluster-prod/archive_spectra 

```

```{r, echo=TRUE, include=FALSE}
# Upload packages

packages <- c( "ggplot2", "scales", "knitr", "markdown", "tidyr", "rmarkdown","gridExtra", "stringr","data.table", "dplyr", "reshape")

if (length(setdiff(packages, rownames(installed.packages()))) > 0) {
    install.packages(setdiff(packages, rownames(installed.packages())), repos="http://cran.us.r-project.org")  }


library("ggplot2");
library("scales");
library("knitr");
library("markdown");

library("tidyr");
library("rmarkdown");
library("gridExtra"); library("stringr");
library("data.table"); library("dplyr");
 library("reshape")

current_release_iden <- "/Users/yperez/cache/CurrentRelease_"
previous_release <- "/Users/yperez/cache/PreviousRelease_"

peptides_iden_current_release <- read.table(paste(current_release_iden, "ID_identify.txt", sep = ""), quote="\"", comment.char="")
peptides_iden_previous_release <- read.table(paste(previous_release, "ID_identify.txt", sep = ""), quote="\"", comment.char="")

```

### **Number of peptides: **
#### **Current Release**

```{r, echo=TRUE}
cat("The number of identified peptides in the Current Release is:", nrow(peptides_iden_current_release))
```

```{r, echo=FALSE, results='asis'}
#Print a frequency tables

table_current_release <- data.frame(Types = c("Identified"), Peptides= c(nrow(peptides_iden_current_release)) )

kable(table_current_release, padding = 0)

```

#### **Previous Release**


```{r, echo=FALSE}
cat("The number of identified peptides in the Previous Release is:", nrow(peptides_iden_previous_release))
```

```{r, echo=FALSE, results='asis'}
table_previous_release <- data.frame(Types = c("Identified"), Peptides= c(nrow(peptides_iden_previous_release)) )

kable(table_previous_release, padding = 0)

```

#### **Summary**

```{r, echo=FALSE, fig.width=10}

#Conditional
if (nrow(peptides_iden_current_release)>nrow(peptides_iden_previous_release)) {
    cat("Number of identified peptides Increased (Current - Previous):", nrow(peptides_iden_current_release)-nrow(peptides_iden_previous_release),"\n")
} else if ((nrow(peptides_iden_current_release)<nrow(peptides_iden_previous_release))) {
    cat("Number of identified Peptides Decreased (Previous - Current):", nrow(peptides_iden_previous_release)-nrow(peptides_iden_current_release),"\n")
} else
    cat("The number of identified peptides are equal \n")


#if (nrow(peptides_unid_current_release)>nrow(peptides_unid_previous_release)) {
#    cat("Number of unidentified peptides reduced:", nrow(peptides_iden_current_release)-nrow(peptides_iden_previous_release),"\n")
#} else if ((nrow(peptides_unid_current_release)<nrow(peptides_unid_previous_release))) {
#    cat("Number of unidentified Peptides increased:", nrow(peptides_unid_previous_release)-nrow(peptides_unid_current_release),"\n")
#} else
#    cat("The number of unidentified peptides are equal \n")


#Create a data.frame with the data. 
df_identified_peptides <- data.frame(Types = c("Current Release Identified", "Previous Release Identified"), Peptides= c(nrow(peptides_iden_current_release),nrow(peptides_iden_previous_release)) )

#df_unidentified_peptides <- data.frame(Types = c("current_release\nUnidentified", "previous_release\nUnidentified"), Peptides= c(nrow(peptides_unid_current_release),nrow(peptides_unid_previous_release)))


#Bar plot
a <- ggplot(df_identified_peptides, aes(x = Types, y = Peptides, fill=Types)) + geom_bar(stat = "identity") + theme(axis.text.x=element_blank(),axis.ticks.x=element_blank()) + scale_y_continuous(expand = c(0, 1000)) 

#b <- ggplot(df_unidentified_peptides, aes(x = Types, y = Peptides, fill=Types)) + geom_bar(stat = "identity") + theme(axis.text.x=element_blank(),axis.ticks.x=element_blank()) + scale_y_continuous(expand = c(0, 100))


#grid.arrange(a, b, ncol=2)

grid.arrange(a, ncol=2)

```


### **Number of modifications: **
#### **Current Release**

```{r, echo=FALSE, message=FALSE, warning=FALSE}

#This part create a modificatons table with the number of medifications en each release and a comparative plot

modifications_current_release <- read.delim(paste(current_release_iden, "tables_modifications_table.txt", sep = ""), header = FALSE)
modifications_previous_release <- read.delim(paste(previous_release, "tables_modifications_table.txt", sep = ""), header=FALSE)



colnames(modifications_current_release) <- c("Modifications", "Frequency")
colnames(modifications_previous_release) <- c("Modifications", "Frequency")


modifications_current_release_1 <- modifications_current_release[order(modifications_current_release$Modifications),] 
modifications_previous_release_2 <- modifications_previous_release[order(modifications_previous_release$Modifications),] 


modifications1 <- cbind(modifications_current_release[1:(nrow(modifications_current_release_1)/2),], modifications_current_release[((nrow(modifications_current_release_1)/2)+1):nrow(modifications_current_release_1),]) 

modifications2 <- cbind(modifications_previous_release[1:(nrow(modifications_previous_release_2)/2),], modifications_previous_release[((nrow(modifications_previous_release)/2)+1):nrow(modifications_previous_release),]) 

cat("There are",nrow(modifications_current_release), " different modifications")
cat("The number of modifications are:", sum(modifications_current_release$Frequency))
kable(modifications1, row.names = FALSE, padding = 0)
```

#### **Previous Release**

```{r, echo=FALSE}

cat("There are",nrow(modifications_previous_release), " different modifications")
cat("The number of modifications are:", sum(modifications_previous_release$Frequency))

kable(modifications2, row.names = FALSE, padding = 0)


```

#### **Summary**


```{r, echo=FALSE, message=FALSE, warning=FALSE}
#Conditional
if (nrow(modifications_current_release)>nrow(modifications_previous_release)) {
    cat("Number of modifications reduced in the new release:", nrow(modifications_current_release)-nrow(modifications_previous_release),"\n")
} else if ((nrow(modifications_current_release)<nrow(modifications_previous_release))) {
    cat("Number of modifications increased in the new release:", nrow(modifications_previous_release)-nrow(modifications_current_release),"\n")
} else
    cat("The number of identified peptides are equal \n")


#Create a df to make it easier
df <- modifications_current_release
df2 <- modifications_previous_release

#First convert your peptide counts to numeric (they're a factor with numeric character labels, that's a bit messed up):

df$Frequency=as.numeric(as.character(df$Frequency))
df2$Frequency=as.numeric(as.character(df2$Frequency))


df_final<- df %>% 
    full_join(df2, by = "Modifications", suffix = c(".1", ".2")) %>%
    # Fix data to convert to character and numeric
    mutate_each(funs(as.numeric(as.character(.))), starts_with("pept")) %>%
    # See difference
    mutate(change = Frequency.2 - Frequency.1)

#How many new peptides are there  in the new release?. 
df_peptides <- df_final[is.na(df_final$Frequency.1),]
df_peptides2 <- data.frame(Modifications=df_peptides$Modifications, Frequency=df_peptides$Frequency.2)

df_peptides3 <- df_final[is.na(df_final$Frequency.2),]
df_peptides4 <- data.frame(Modifications=df_peptides3$Modifications, Frequency=df_peptides3$Frequency.2)

```

```{r, echo=FALSE, warning=FALSE}
#To know if the new release has obtained new peptides. 
if (nrow(df_final[is.na(df_final$Frequency.1),])!=0) {
    cat("The new release has obtained new peptides")
    kable(df_peptides2, padding = 0)
} else if (nrow(df_final[is.na(df_final$Frequency.2),])!=0) {
    cat("The new release has lost peptides\n")
    kable(df_peptides4, padding = 0)
} else
   cat("The new release has got the same peptides")



```


```{r, echo=FALSE}
#HISTOGRAM: 
#Para preparar el histograma tenemos que clasificar los tipos de modificaciones, POSICION-DATABA-ID. 
# Para ello cogemos los datos que no sean NULL y eliminamos los espacios en banco. 

histo1 = subset(df, Modifications != 'NULL')
histo1[histo1==""] <- NA
histo1 = subset(histo1, Modifications != 'NA')

histo1_2 = subset(df2, Modifications != 'NULL')
histo1_2[histo1_2==""] <- NA
histo1_2 = subset(histo1_2, Modifications != 'NA')

#Split dataset. 
histo2 <- data.frame(str_split_fixed(histo1$Modifications, ",", 20))
histo2_2 <- data.frame(str_split_fixed(histo1_2$Modifications, ",", 20))

#If you want to check how many columns are empty, you can use the code below: 
#columns_emply <- histo2[!sapply(histo2, function(x) all(x == ""))]
#columns_emply <- histo2_2[!sapply(histo2_2, function(x) all(x == ""))]

#Merge the columns in one. 
histo3 <- melt(setDT(histo2),                              # set df to a data.table
               measure.vars = list(c(1:20)),    # set column groupings
               value.name = 'V1')[                      # set output name scheme
                   , -1, with = F]

histo3_2 <- melt(setDT(histo2_2),                              # set df to a data.table
                 measure.vars = list(c(1:20)),    # set column groupings
                 value.name = 'V1')[                      # set output name scheme
                     , -1, with = F]

#Remove white rows.  
histo3[histo3==""] <- NA
histo3 = subset(histo3, V1 != " ")

histo3_2[histo3_2==""] <- NA
histo3_2 = subset(histo3_2, V1 != " ")

#Remove first part of the string [num]-
histo4 <- data.frame(modifications=gsub(" [A-Za-z] ", "", gsub("[0-9]*-", "", histo3$V1)))
histo4_2 <- data.frame(modifications.2=gsub(" [A-Za-z] ", "", gsub("[0-9]*-", "", histo3_2$V1)))

#Histograma: 
histo5 <- data.frame(table(histo4))
histo5_2 <- data.frame(table(histo4_2))

# ggplot(data=histo5, aes(x=histo4, y=Freq, fill=histo4)) +
#     geom_bar(stat="identity") + guides(fill=FALSE)+ 
#     theme(axis.text.x = element_text(angle = 90, hjust = 1))
# 
# ggplot(data=histo5_2, aes(x=histo4_2, y=Freq, fill=histo4_2)) +
#     geom_bar(stat="identity") + guides(fill=FALSE)+ 
#     theme(axis.text.x = element_text(angle = 90, hjust = 1))

```

```{r, echo=FALSE, fig.height=15, fig.width=25, message=FALSE, warning=FALSE}
#We're going to compare different releases in order to compare between them and create a stacker plot.

histo5 <- modifications_current_release
histo5_2 <- modifications_previous_release

colnames(histo5) <- c("Modifications","Frequency")
colnames(histo5_2) <- c("Modifications","Frequency")

histo6<-merge(histo5,histo5_2, by = "Modifications",all = T)


histo7<- melt(histo6)
histo7$variable<-factor(histo7$variable,labels = c("Modifications1","Modifications2"))


ggplot(histo7, aes(x = Modifications, y = value, fill = variable)) + 
  geom_bar(stat = "identity",position = "dodge")+
    theme(axis.text.x = element_text(angle = 20, hjust = 0.5, vjust = -0.1)) + 
    guides(fill=FALSE)+
    labs("Barplot current_release vs Previous Release") + 
    xlab("Values")+
    ylab("Frequency")+
    theme(text = element_text(size=18), axis.text.x = element_text(angle = 90, hjust = 1, size = 15), 
          axis.text.y=element_text(size = 15))

```

### **Spectrum**

```{r, echo=FALSE, message=FALSE, warning=FALSE}
#Here is the same than before examples.

spectrum_iden_current_release <- read.delim(paste(current_release_iden, "tables_spectrum_ide_table.txt", sep=""), header = TRUE)
spectrum_iden_previous_release <- read.delim(paste(previous_release, "tables_spectrum_ide_table.txt", sep = ""), header = TRUE)

```

#### **Current Release **
```{r, echo=FALSE, message=FALSE, warning=FALSE}
cat("The number of identified spectrum in the Current Release is:", spectrum_iden_current_release$Spectrum.Number)
cat("The number of identified spectrum in the previous_release  is:", spectrum_iden_previous_release$Spectrum.Number)

```

#### **Previous Release**
```{r, echo=FALSE, message=FALSE, warning=FALSE}
cat("The number of identified spectrum in the Current Release  is: ", spectrum_iden_current_release$Spectrum.Number)
cat("The number of identified spectrum in the Previous Release is: ", spectrum_iden_previous_release$Spectrum.Number)
```

#### **Summary**
```{r, echo=FALSE, message=FALSE, warning=FALSE}
#for identified
if (spectrum_iden_current_release$Spectrum.Number>spectrum_iden_previous_release$Spectrum.Number) {
    cat("Number of identified spectrum reduced:", spectrum_iden_current_release$Spectrum.Number-spectrum_iden_previous_release$Spectrum.Number,"\n")
} else if ((spectrum_iden_current_release$Spectrum.Number<spectrum_iden_previous_release$Spectrum.Number)) {
    cat("Number of identified spectrum Peptides increased:", spectrum_iden_previous_release$Spectrum.Number-spectrum_iden_current_release$Spectrum.Number,"\n")
} else
    cat("The number of identified spectrum is the same in both releases \n")


#For unidentified
#if (spectrum_unid_current_release$Spectrum.Number>spectrum_unid_previous_release$Spectrum.Number) {
#    cat("Number of unidentified spectrum reduced:", spectrum_unid_current_release$Spectrum.Number-spectrum_unid_previous_release$Spectrum.Number,"\n")
#} else if ((spectrum_unid_current_release$Spectrum.Number<spectrum_unid_previous_release$Spectrum.Number)) {
#    cat("Number of unidentified spectrum Peptides increased:", spectrum_unid_previous_release$Spectrum.Number-spectrum_unid_current_release$Spectrum.Number,"\n")
#} else
#    cat("The number of unidentified spectrum is the same in both releases \n")


```

### **Taxonomy** 
#### **Current Release**

```{r, echo=FALSE}

taxonomy_iden_current_release <- read.delim(paste(current_release_iden, "tables_taxonomy_ide_table.txt", sep = ""), header = FALSE)

taxonomy_iden_previous_release <- read.delim(paste(previous_release, "tables_taxonomy_ide_table.txt", sep = ""), header = FALSE)

colnames(taxonomy_iden_current_release) <- c("Taxonomy", "Frequency")
colnames(taxonomy_iden_previous_release) <- c("Taxonomy", "Frequency")


cat("Number of species in the Current Release is:", nrow(taxonomy_iden_current_release))
cat("The total taxonomy for identified peptides in the Current Release is:", sum(taxonomy_iden_current_release$Frequency))


```

#### **Previous Release**

```{r, echo=FALSE}

cat("Number of species in the Previous Release is:", nrow(taxonomy_iden_previous_release))
cat("The total taxonomy for identified peptides in the Previous Release is:", sum(taxonomy_iden_previous_release$Frequency))


```

### **Summary**

```{r, echo=FALSE}

#Conditional
if (sum(taxonomy_iden_current_release$Frequency)>sum(taxonomy_iden_previous_release$Frequency)) {
    cat("Identified peptides from Taxonomy reduced in the new release:", nrow(taxonomy_iden_current_release$Frequency)-nrow(taxonomy_iden_previous_release$Frequency),"\n")
} else if ((sum(taxonomy_iden_current_release$Frequency)<sum(taxonomy_iden_previous_release$Frequency))) {
    cat("Identified peptides from Taxonomy increased in the new release:", sum(taxonomy_iden_previous_release$Frequency)-sum(taxonomy_iden_current_release$Frequency),"\n")
} else
    cat("Taxonomy peptides are equal in both releases \n")


#Conditional
#if (sum(taxonomy_unid_current_release$Frequency)>sum(taxonomy_unid_previous_release$Frequency)) {
#    cat("Identified peptides from Taxonomy reduced in the new release:", nrow(taxonomy_unid_current_release$Frequency)-nrow(taxonomy_unid_previous_release$Frequency),"\n")
#} else if ((sum(taxonomy_unid_current_release$Frequency)<sum(taxonomy_unid_previous_release$Frequency))) {
#    cat("Identified peptides from Taxonomy increased in the new release:", sum(taxonomy_unid_previous_release$Frequency)-sum(taxonomy_unid_current_release$Frequency),"\n")
#} else
#    cat("Taxonomy peptides are equal in both releases \n")
```

```{r, echo=FALSE}

taxonomy_iden_current_release <- read.delim(paste(current_release_iden, "tables_taxonomy_ide_table.txt", sep = ""), header = FALSE)

taxonomy_iden_previous_release <- read.delim(paste(previous_release, "tables_taxonomy_ide_table.txt", sep = ""), header = FALSE)

colnames(taxonomy_iden_current_release) <- c("Taxonomy", "Frequency")
colnames(taxonomy_iden_previous_release) <- c("Taxonomy", "Frequency")

taxonomy_iden_current_release$Taxonomy <- as.factor(taxonomy_iden_current_release$Taxonomy)
taxonomy_iden_previous_release$Taxonomy <- as.factor(taxonomy_iden_previous_release$Taxonomy)


#Create table
taxonomy_table_iden<-merge(taxonomy_iden_current_release,taxonomy_iden_previous_release, by = "Taxonomy",all = T)

library(reshape2)
taxonomy_table_iden2<- melt(taxonomy_table_iden)


taxonomy_table_iden2$variable<-factor(taxonomy_table_iden2$variable,labels = c("Taxonomy1","Taxonomy2"))



ggplot(taxonomy_table_iden2, aes(x = Taxonomy, y = value, fill = variable)) + 
  geom_bar(stat = "identity",position = "dodge")+
    theme(axis.text.x = element_text(angle = 20, hjust = 0.5, vjust = -0.1)) + 
    guides(fill=FALSE)+
    labs("Barplot current_release vs Previous Release") + 
    xlab("Values")+
    ggtitle("Identified Taxonomy")+
    ylab("Frequency")+
    theme(text = element_text(size=18), axis.text.x = element_text(angle = 90, hjust = 1, size = 15), 
          axis.text.y=element_text(size = 15))

#ggplot(taxonomy_table_unid2, aes(x = Taxonomy, y = value, fill = variable)) + 
#  geom_bar(stat = "identity",position = "dodge")+
#    theme(axis.text.x = element_text(angle = 20, hjust = 0.5, vjust = -0.1)) + 
#    guides(fill=FALSE)+
#    labs("Barplot current_release vs Previous Release") + 
#    ggtitle("Unidentified Taxonomy")+
#    xlab("Values")+
#    ylab("Frequency")+
#    theme(text = element_text(size=18), axis.text.x = element_text(angle = 90, hjust = 1, size = 15), 
#          axis.text.y=element_text(size = 15))

```

